[tool.poetry]
authors = ["Chas Holloway <aws.testing0101@gmail.com>"]
description = ""
name = "dev-infrastructure"
package-mode = false
version = "1.0.0"

[[tool.poetry.source]]
name = "test"
url = "https://pypi-596075413947.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple"
priority = "supplemental"

[[tool.poetry.source]]
name = "m3ce_upload"
url = "https://pypi-596075413947.d.codeartifact.us-east-1.amazonaws.com/pypi/python"
priority = "supplemental"

[tool.poetry.dependencies]
cached_property = "*"
click = ">=8"
inforclients = "*"
jira = "*"
kubernetes = "^12.0.1"
pygit2 = ">=1.0.3,<2"
python = ">3.11,<4"
pyyaml = "*"
typer = "*"
more-itertools = "^9.1.0"
urllib3 = "<1.27,>=1.25.4"
awscli = "^1.27.145"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
cfn-lint = "*"
flake8 = ">=4"
invoke = "*"
pyflakes = "*"
pytest = "*"
pytest-cov = "*"
pytest-env = "*"
pytest-mock = "*"
responses = "<1.26"
urllib3 = "<1.27,>=1.25.4"
yamllint = "*"

[tool.coverage]
[tool.coverage.run]
omit = ["*test_*", "*__init__*", ".venv/*"]
[tool.coverage.report]
skip_empty = true

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
